### ISSUE TITLE
terminal-notifier -remove creates blank notifications

### ISSUE THREAD

**Issue by eerie444** [petere/homebrew-auto-update#1]
I haven't been able to determine whether this is a bug with homebrew-auto-update, or one with terminal-notifier. As you know, `terminal-notifier -remove` is buggy (alloy/terminal-notifier#118). This issue is distinct from that one, however.

When homebrew-auto-update finds that no apps are outdated, it asks terminal-notifier to remove any previous notifications in group `org.eisentraut.BrewAutoUpdate`. When there aren't any previous notifications, terminal-notifier should do nothing. But instead, it creates a blank notification:

```
$ terminal-notifier -list ALL
GroupID Title   Subtitle    Message Delivered At
(null)  Terminal    (null)      2015-04-17 20:09:03 +0000
(null)  Terminal    (null)      2015-04-17 19:38:42 +0000
(null)  Terminal    (null)      2015-04-17 18:57:17 +0000
```

This happens whenever launchd runs brew-auto-update. The bizarre thing is, if I run brew-auto-update or terminal-notifier manually, no notifications are created:

```
 $ brew-auto-update
 $ terminal-notifier -list ALL
 $ terminal-notifier -remove 'org.eisentraut.BrewAutoUpdate' >/dev/null
 $ terminal-notifier -list ALL
 $
```

I'm on Yosemite (10.10.3), running terminal-notifier 1.6.3.

**Comment by glangford** [comment]
+1. I see the same behaviour with terminal-notifier 1.6.3.
